version: "3"

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "secret"

  web:
    depends_on:
    - postgres
    build: .
    ports:
    - "3000:3000"
    - "9229:9229"
    restart: always
    environment:
      NODE_ENV: development
      PORT: 3000
      DBPASSWORD: secret
      DBHOST: postgres
      JWTSECRET: secret
