openapi: 3.0.1
info:
  title: API description
  version: 0.0.1
paths:
  /api/user:
    get:
      summary: Users list
      security:
      - bearerAuth: []
      responses:
        200:
          description: OK
        401:
          description: Unauthorized
    post:
      summary: Registration
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  description: New user Email
                  type: string
                password:
                  description: New user Password
                  type: string
                  format: password
              required:
              - email
              - password
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  id:
                    type: integer
                  email:
                    type: string
                  createdAt:
                    type: object
  /api/login:
    post:
      summary: Authorization
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  description: New user Email
                  type: string
                password:
                  description: New user Password
                  type: string
                  format: password
              required:
              - email
              - password
        required: true
      responses:
        200:
          description: OK
  /api/me:
    get:
      summary: My authorized account
      security:
      - bearerAuth: []
      responses:
        200:
          description: OK
        401:
          description: Unauthorized
  /api/deal:
    get:
      summary: Deals list
      security:
      - bearerAuth: []
      responses:
        200:
          description: OK
        403:
          description: Forbidden
    post:
      summary: Create new deal
      security:
      - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                receiver:
                  description: User ID
                  type: integer
                message:
                  type: string
                price:
                  type: number
              required:
              - receiver
              - message
              - price
        required: true
      responses:
        200:
          description: OK
        403:
          description: Forbidden
  /api/deal/{dealId}/activity:
    get:
      summary: Deals activities list
      security:
      - bearerAuth: []
      parameters:
      - name: dealId
        in: path
        required: true
        schema:
          type: number
      responses:
        200:
          description: OK
        403:
          description: Forbidden
    post:
      summary: Create new deal activity
      security:
      - bearerAuth: []
      parameters:
      - name: dealId
        in: path
        required: true
        schema:
          type: number
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  default: ''
                price:
                  type: number
                  description: Set -1 to decline
              required:
              - message
        required: true
      responses:
        200:
          description: OK
        403:
          description: Forbidden
  /api/deal/{dealId}/accept:
    post:
      summary: Accept deal
      security:
      - bearerAuth: []
      parameters:
      - name: dealId
        in: path
        required: true
        schema:
          type: number
      responses:
        200:
          description: OK
        403:
          description: Forbidden
  /api/deal/{dealId}/access:
    get:
      summary: Deal access rights
      security:
      - bearerAuth: []
      parameters:
      - name: dealId
        in: path
        required: true
        schema:
          type: number
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  canAnswer:
                    type: boolean
        403:
          description: Forbidden
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
